version: '3'
services:
  backend:
    volumes:
      - ./backend:/backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    # depends_on:
    #   - "mysql"

  nginx: 
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./nginx:/usr/share/nginx/html
    depends_on:
      - backend

#   mysql:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: go_database
#       MYSQL_USER: go_test
#       MYSQL_PASSWORD: password
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     ports:
#       - 3306:3306
